PFN-108: https://ru.yougile.com/team/343b17e1c7b0/#PFN-108
frontend-park-mail-ru/2024_2_EaglesDesigners pull request #32
Opened 2024-10-16 22:26 UTC by MoyStasik

базовая версия роутера. Ссылка на задачу - https://ru.yougile.com/team/343b17e1c7b0/#PFN-108

2024-10-18 22:08 UTC, rissenberg requested changes

2024-10-18 22:08 UTC, rissenberg commented on source/shared/Router.ts
> +    constructor () {
Смотри следующие замечания: передавай сюда файл конфига и декомпозируй его на routes, strictRoutes, defaultAuthRoute, defaultUnauthRoute, например

2024-10-18 22:08 UTC, rissenberg commented on source/shared/Router.ts
> +        if (index >= 0 && authResult ) {
`index !== -1`, так понятнее разработчику

2024-10-18 22:08 UTC, rissenberg commented on source/shared/Router.ts
> +            console.log(currentURL);
Все консоль логи из мр в мастер убирай

2024-10-18 22:08 UTC, rissenberg commented on source/shared/api/api.ts
> +export const API = new Api("http://localhost:8080");
Забыл вернуть?

2024-10-18 22:08 UTC, rissenberg commented on source/shared/api/types.ts
>  import { TChat } from "@/entities/Chat";
Импорты пишутся только в начале

2024-10-18 22:08 UTC, rissenberg commented on source/shared/api/types.ts
> +interface configRoute{
Эти типы тут не должны быть. Лучше вынеси в отдельную папку /shared/router и типы, и сам роутер

2024-10-18 22:08 UTC, rissenberg commented on source/pages/MainPage/ui/MainPage.ts
> +  constructor(router : Router) {
Пример - класс API у вас

2024-10-18 23:05 UTC, MoyStasik commented on source/app/View.ts
> +export class View {
тайп скрипт ругался что нет render у view

2024-10-18 23:25 UTC, MoyStasik commented on source/shared/Router.ts
> +    constructor () {
Теперь экспортирую единственный экземпляр роутера, поэтому чтобы не писать пути в самом роутере, конструктор будет инициализировать по умолчанию, а в app все руты поделил на 3 типа

2024-10-19 17:04 UTC, rissenberg requested changes

2024-10-19 17:04 UTC, rissenberg commented on source/shared/api/types.ts
> +export interface ChatModel {
Если вы его добавили в entity/Chat/type, то удалите отсюда, он здесь точно не нужен

2024-10-19 17:04 UTC, rissenberg commented on source/shared/api/types.ts
> +export type ChatListModel = ChatModel[];
И это тоже

2024-10-19 17:04 UTC, rissenberg commented on source/widgets/loginForm/ui/loginForm.ts
> +import { RouterObj as Router } from "@/shared/Router/Router";
Давай его сразу называть просто Router

2024-10-19 17:04 UTC, rissenberg commented on source/widgets/loginForm/ui/loginForm.ts
> +import { user as User } from "@/app/User";
Здесь тоже не мудри - просто UserStorage

2024-10-19 17:35 UTC, MoyStasik commented on source/app/View.ts
> +export class View {
Тайпскрипт ругается тогда, что у наших view в роутере нет метода render, поэтому все классы, которые отвечают за рендер страницы расширил class View, тогда тайпскрипт перестал ругаться

2024-10-19 17:46 UTC, rissenberg requested changes

2024-10-19 17:46 UTC, rissenberg commented on source/app/App.ts
> +import { UserStroage } from "@/entities/User/lib/UserStroage.ts";
Добавь экспорт в /entity/User/index.ts и сократи этот импорт

Всегда когда добавляешь какие то классы и функции на экспорт из слайса пиши их в паблик апи - index.ts

2024-10-19 17:46 UTC, rissenberg commented on source/entities/Chat/model/type.ts
> +export interface ChatModel {
Дублирует предыдущий тип, удали его

2024-10-19 17:46 UTC, rissenberg commented on source/entities/User/lib/UserStroage.ts
> +class UserStore {
Сделай одинаковым нейминг у файла и у класса - какой сам выберешь

2024-10-19 17:46 UTC, rissenberg commented on source/entities/User/lib/UserStroage.ts
> +UserStroage.init();
эта строка сработает при первом вызове UserStore - успеет ли он сделать фетч?


Давай лучше в классе App при инициализации приложения его вызывать вместе с await - так надежнее

2024-10-19 17:46 UTC, rissenberg commented on source/pages/MainPage/ui/MainPage.ts
> +    const user = localStorage.getItem("user");
Вынеси эту логику в UserStore и здесь дергай его методы

2024-10-19 17:46 UTC, rissenberg commented on source/pages/MainPage/ui/MainPage.ts
> +    const user = localStorage.getItem("user");
Предлагаю вместо localStorage хранить инфу прямо в классе UserStore в его this полях - `this.user: IUser`

2024-10-19 19:16 UTC, MoyStasik commented on source/app/App.ts
> +import { UserStroage } from "@/entities/User/lib/UserStroage.ts";
сделал

2024-10-19 20:22 UTC, MoyStasik commented on source/pages/MainPage/ui/MainPage.ts
> +    const user = localStorage.getItem("user");
сделал

2024-10-19 20:22 UTC, MoyStasik commented on source/entities/User/lib/UserStroage.ts
> +UserStroage.init();
сделал

2024-10-19 20:24 UTC, MoyStasik commented on source/widgets/loginForm/ui/loginForm.ts
> +import { user as User } from "@/app/User";
Сделал

2024-10-19 20:29 UTC, MoyStasik commented on source/shared/api/types.ts
> +interface configRoute{
сделал

2024-10-19 20:30 UTC, MoyStasik commented on source/app/User.ts
> +import { API } from "@/shared/api/api";
сделал

2024-10-19 20:30 UTC, MoyStasik commented on source/pages/SignupPage/ui/SignupPage.ts
> +  async render() {
убрал

2024-10-19 21:03 UTC, rissenberg requested changes

2024-10-19 21:03 UTC, rissenberg commented on source/entities/User/lib/UserStore.ts
> +  setUserName(nick: string) {
Давай методы звать getUser и setUser и пусто они работают с полным объектом. В логине и сигнапе передавай в set тот объект, что в response лежит

2024-10-19 21:05 UTC, MoyStasik commented on source/entities/User/index.ts
> -export { TUser } from './model/type.ts';
сделал

2024-10-19 21:22 UTC, MoyStasik commented on source/app/App.ts
>      const response = await API.get<AuthResponse>("/auth");
вернул

2024-10-19 21:22 UTC, MoyStasik commented on source/entities/User/lib/UserStore.ts
> +  setUserName(nick: string) {
сделал

2024-10-19 21:24 UTC, MoyStasik commented on source/app/BackUrl.ts
> +export const localHost = "http://localhost:8080";
вернул

2024-10-19 21:34 UTC, rissenberg approved these changes

2024-10-19 21:34 UTC, merged