PFN-111: Сверстать чат и настроить отправку сообщений через WebSocket
frontend-park-mail-ru/2024_2_EaglesDesigners pull request #33
Opened 2024-10-30 21:55 UTC by vovasvl

Ссылка на задачу: https://ru.yougile.com/team/343b17e1c7b0/Patefon#PFN-111

2024-11-01 10:11 UTC, rissenberg requested changes

2024-11-01 10:11 UTC, rissenberg commented on source/pages/MainPage/ui/MainPage.ts
> +    const renderMessage = (message:TChatMessage) =>{
Точно этот обработчик должен находиться в MainPage?

2024-11-01 10:11 UTC, rissenberg commented on source/shared/api/ws.ts
> +export const wsConn = new wsConnection("http://localhost:8080/chat/startwebsocket");
URL можно вынести в файл с константами, у вас он вроде бы есть

2024-11-01 10:11 UTC, rissenberg commented on source/widgets/Chat/ui/Chat.handlebars
> +                {{replaceChatType chat.chatType}}
Аналогично, в js привести переменную chatType к нужному виду и потом ее уже передавать

2024-11-01 10:11 UTC, rissenberg commented on source/widgets/Chat/ui/Chat.ts
> +      let messages: TChatMessage[] = [];
можно обойтись без let и написать объявление так: `const messages = response.messages ?? [];`

2024-11-01 10:11 UTC, rissenberg commented on source/widgets/Chat/ui/Chat.ts
> +      let messages: TChatMessage[] = [];
надеюсь вы помните как работют цепочки операторов &&, || и ??

2024-11-01 10:11 UTC, rissenberg commented on source/widgets/SignUp/ui/signUpForm.ts
> +      UserStorage.setUser({ id: "", name: nickname, username: login });
а нужно ли при логауте закрывать соединение вебсокета?

2024-11-01 10:11 UTC, rissenberg commented on source/widgets/SignUp/ui/signUpForm.ts
> +      UserStorage.setUser({ id: "", name: nickname, username: login });
и поправь, пожалуйста, логику здесь, чтобы юзер устанавливался полностью, как в форме логина

и тут тоже нужно инициировать вебсокет соединение

2024-11-01 11:44 UTC, vovasvl commented on helpers/extractTime.js
> +module.exports = function(datetime) {
У меня хелперы импортируются только в конфиг вебпака для параметров handlebars-loader, чтобы они в шаблонах распознавались. Никакие компоненты в source не импортируют в себя хелперы, их точно лучше переместить в shared?

2024-11-01 11:45 UTC, vovasvl commented on helpers/extractTime.js
> +module.exports = function(datetime) {
Или вообще убрать хелперы и менять нужные поля message перед тем, как кидать объект в шаблон handlebars?

2024-11-01 12:05 UTC, vovasvl commented on source/widgets/SignUp/ui/signUpForm.ts
> +      UserStorage.setUser({ id: "", name: nickname, username: login });
Мне кажется, нужно закрывать соединение после логаута, т.к. если войти в другой аккаунт после логаута, то останется прошлое соединение, а новое не откроется и с сервера будут приходить сообщения для прошлого аккаунта, а не текущего. Или стоит как-то по-другому реализовать?

2024-11-04 09:34 UTC, rissenberg commented on helpers/extractTime.js
> +module.exports = function(datetime) {
Да, как сказал во втором сообщении

2024-11-04 09:55 UTC, rissenberg commented on source/app/config.ts
> +export const ChatLabel = {
nit: если таких параметров будет много, лучше их вынести в отдельный файл и назвать например locales

2024-11-04 09:55 UTC, rissenberg commented on source/widgets/SignUp/ui/signUpForm.ts
> +      UserStorage.setUser({ id: "", name: nickname, username: login });
Да, все так. Вижу, что добавил

2024-11-04 09:59 UTC, rissenberg approved these changes

2024-11-04 10:34 UTC, merged