PFN-125: Рефактор стилей
frontend-park-mail-ru/2024_2_EaglesDesigners pull request #48
Opened 2024-11-13 02:18 UTC by vovasvl

Ссылка на задачу: https://ru.yougile.com/team/343b17e1c7b0/Patefon#PFN-125

Это немного, но это честная работа

2024-11-14 20:20 UTC, rissenberg requested changes

2024-11-14 20:20 UTC, rissenberg commented on source/widgets/ChatList/ui/ChatList.scss
> +  margin-top: $chat-margin-top;
А это маржин за что отвечает?

2024-11-14 20:20 UTC, rissenberg commented on source/widgets/GroupChatInfo/ui/GroupChatInfo.scss
> +  margin-left: 10px;
Можно объединить в один стиль

2024-11-14 20:29 UTC, vovasvl commented on source/pages/MainPage/ui/MainPage.scss
> +  margin-right: 20px;
Тогда после списка чатов пробел некрасивый появляется

![image](https://github.com/user-attachments/assets/debfef11-3ea4-4cbb-a856-bba793cb9328)
![image](https://github.com/user-attachments/assets/971c3f6c-dab2-4e6f-9369-cecf437cf729)

2024-11-14 20:30 UTC, vovasvl commented on source/pages/MainPage/ui/MainPage.scss
>    background: transparent;
До MainPage пока не добрался рефакторить, это еще не менял

2024-11-16 00:46 UTC, vovasvl commented on source/pages/MainPage/ui/MainPage.scss
> +  height: calc(100% - $chat-margin-top);
Хз, без отступа как-то странно выглядит
![image](https://github.com/user-attachments/assets/7de27d70-d206-4a92-8d69-0e2237828b70)

2024-11-16 00:51 UTC, vovasvl commented on source/widgets/ChatList/ui/ChatList.scss
> +  margin-top: $chat-margin-top;
За то, чтобы у поиска, чата и бабла инфы о чате был одинаковый отступ сверху

2024-11-17 00:00 UTC, vovasvl commented on source/pages/MainPage/ui/MainPage.ts
> +    const chatParent = parent.querySelector(".chat-content")!;
Он возвращает и по классам, и по id, и даже регулярки можно использовать

2024-11-17 00:02 UTC, vovasvl commented on source/pages/MainPage/ui/MainPage.ts
> +    const chatParent = parent.querySelector(".chat-content")!;
Я переписал все querySelector по id, т.к. они уникальные и чтобы точно нужный элемент получали, а не один из элементов с одинаковым классом

2024-11-19 16:15 UTC, rissenberg approved these changes

2024-11-19 16:16 UTC, rissenberg commented on source/widgets/ChatList/ui/ChatList.scss
> +  margin-top: $chat-margin-top;
Я бы предложил у контейнера делать padding-top, но на ваше усмотрение

2024-11-19 16:19 UTC, merged