PFN-126: фикс профиля, роутера, кнопки для удаления, скрол в чате
frontend-park-mail-ru/2024_2_EaglesDesigners pull request #49
Opened 2024-11-15 12:48 UTC by MoyStasik

Подключил апишку для чатов, исправил по верстке отступы и placeholder'ы для профиля.
Ссылка на задачу - https://ru.yougile.com/team/343b17e1c7b0/#PFN-126

2024-11-15 23:16 UTC, rissenberg requested changes

2024-11-15 23:16 UTC, rissenberg commented on source/widgets/ChatInfo/ui/ChatInfo.ts
>        }
Можно в принципе тернарник завести, условие не такое большое. Его можно прямо в [ ] засунуть, делая выбор между 1 или 0

2024-11-15 23:16 UTC, rissenberg commented on source/widgets/ContactAddForm/ui/ContactAddForm.ts
> +      if (response.error === "Contact already exists") {
Я помню Вове предлагал завести словарь с ошибками - у нас он есть? Если есть - заведи в нем эти ошибки в качестве ключей, а значением у них будет текст на русском языке - так можно будет передавать ошибку (если она есть!) и получать текст для отображения - и миллион ифов не нужны

А если словаря еще нет - заведи :) 
Предлагаю в shared/config/lang.ts

2024-11-15 23:16 UTC, rissenberg commented on source/widgets/GroupChatInfo/ui/GroupChatInfo.scss
> +    background-color: red;
Не слишком ли ярко? Если уж и дефолтные использовать - то я бы выбрал tomato, он менее вырвиглазный

2024-11-15 23:16 UTC, rissenberg commented on webpack.config.js
> +// eslint-disable-next-line @typescript-eslint/no-require-imports
Не, так дело не пойдет. Лучше исключи из конфига линтера этот файл или корневую папку, укажи, чтобы смотрел только /source

2024-11-16 19:37 UTC, MoyStasik commented on source/widgets/ChatInfo/ui/ChatInfo.scss
> +  &__button {
сделал

2024-11-16 19:37 UTC, MoyStasik commented on source/widgets/GroupChatInfo/ui/GroupChatInfo.scss
> +    background-color: red;
сделал

2024-11-16 19:38 UTC, MoyStasik commented on source/widgets/ChatInfo/ui/ChatInfo.scss
> +  padding: 0px 20px 0px 20px  ;
сократил

2024-11-16 19:38 UTC, MoyStasik commented on source/shared/Router/Router.ts
> +      if (event.state) {
сделал

2024-11-16 19:50 UTC, MoyStasik commented on webpack.config.js
> +// eslint-disable-next-line @typescript-eslint/no-require-imports
исправил

2024-11-16 19:50 UTC, MoyStasik commented on source/widgets/ChatInfo/ui/ChatInfo.ts
>        }
сделал

2024-11-17 16:30 UTC, rissenberg requested changes

2024-11-17 16:30 UTC, rissenberg commented on source/widgets/ContactAddForm/ui/ContactAddForm.ts
> +      if (response.error in errors) {
а если такой ошибки не будет в errors? тут лучше проверять само наличие ошибки response.error, а если такой не будет найдено в errors, то написать ошибку по умолчанию (ее бы тоже в константу выделить в lang)

2024-11-17 22:11 UTC, rissenberg requested changes

2024-11-17 22:11 UTC, rissenberg commented on source/widgets/ContactAddForm/ui/ContactAddForm.ts
> +        }
`const message = errors[response.error] ?? errors['Default error'];

2024-11-17 22:22 UTC, rissenberg approved these changes

2024-11-17 22:22 UTC, merged