PFN 138: Сделать поиск продуктовые + PFN-125, PFN-129
frontend-park-mail-ru/2024_2_EaglesDesigners pull request #51
Opened 2024-11-24 17:14 UTC by MoyStasik

ссылка на задачу - https://ru.yougile.com/team/343b17e1c7b0/#PFN-138

2024-11-24 19:34 UTC, rissenberg requested changes
В тех файлах в которых не оставил комментариев скорее всего тоже есть те ошибки, о которых я говорил - проверь все сам

2024-11-24 19:34 UTC, rissenberg commented on source/entities/SearchedMessageCard/ui/SearchedMessageCard.ts
> +        }
сделай через цепочку логический операторов

2024-11-24 19:34 UTC, rissenberg commented on source/entities/SearchedMessageCard/ui/SearchedMessageCard.ts
> +            let message : HTMLElement = chatMessages.querySelector("[id='" + messageId + "']")!;
обратные кавычки

2024-11-24 19:34 UTC, rissenberg commented on source/entities/SearchedMessageCard/ui/SearchedMessageCard.ts
> +                    const response = await API.get<ChatMessagesResponse>("/chat/" + ChatStorage.getChat().chatId + "/messages/pages/" + chatMessages.lastElementChild?.id)!;
обратные кавычки

2024-11-24 19:34 UTC, rissenberg commented on source/entities/SearchedMessageCard/ui/SearchedMessageCard.ts
> +                message = chatMessages.querySelector("[id='" + messageId + "']")!;
обратные кавычки. даже писать уже устал. посмотри сам далее, где они еще встречаются в твоем коде, и исправь самостоятельно

2024-11-24 19:34 UTC, rissenberg commented on source/pages/MainPage/ui/handlers.ts
> +  // if (message.authorID === UserStorage.getUser().id) {
убрать

2024-11-24 19:34 UTC, rissenberg commented on source/shared/helpers/debounce.ts
> +      if (previousCall && this.lastCall - previousCall <= timeoutMs) {
зачем сверять время? очищай таймаут в любом случае, если он пустой - ничего не случится. если есть - то очиститься и начнется новый

2024-11-24 19:34 UTC, rissenberg commented on source/widgets/AddChannelForm/index.ts
пустые файлы не оставляем

2024-11-24 19:34 UTC, rissenberg commented on source/widgets/AddChannelForm/lib/types.ts
> +export interface UserType{
как то глупо - ты же не можешь бытб и одним и другим? тогда валиднее сделать тип UserType = 'owner' | 'admin' | 'user'

2024-11-24 19:34 UTC, rissenberg commented on source/widgets/Chat/ui/Chat.handlebars
> +    {{#if userType.owner}}
`userType === 'owner'` и тд

2024-11-24 19:34 UTC, rissenberg commented on source/widgets/DeleteMessage/ui/DeleteMessage.ts
> +                spanDelete.textContent = "Вы не можете удалять чужие сообщения";
вы хоть делаете пре проверку чтобы это сообщение ни в каком кейсе не показалось?

2024-11-24 19:34 UTC, rissenberg commented on source/widgets/GroupChatInfo/ui/GroupChatInfo.handlebars
> +  <button id="delete-group" class="delete-group__button">{{#if userType.owner}}{{#if chatType.group}}Удалить группу{{else}}Удалить канал{{/if}}{{else}}{{#if chatType.group}}Выйти из группы{{else}}Вый
все слиплось. на разных строках сделай эти выборы

2024-11-24 19:48 UTC, MoyStasik commented on source/entities/ChatCard/ui/ChatCard.ts
> +        const currentChat = document.querySelector("[id='" + ChatStorage.getChat().chatId + "']")!;
была проблема, есть id которые с цифры начинаются, ругается на них

2024-11-24 19:49 UTC, MoyStasik commented on source/entities/ChatMessage/ui/ChatMessage.handlebars
> +  id="{{message.messageId}}"
у нас же у каждого сообщения свой id, не должно быть конфликта, если правильно понял вопрос

2024-11-24 19:55 UTC, MoyStasik commented on source/entities/ChatMessage/ui/ChatMessage.ts
> +      let avatarURL;
вернул

2024-11-24 19:56 UTC, MoyStasik commented on source/entities/ChatMessage/ui/ChatMessage.ts
> +      let avatarURL;
чтобы проверить существует ли аватарка

2024-11-24 19:59 UTC, MoyStasik commented on source/widgets/GroupChatInfo/ui/GroupChatInfo.handlebars
> +  <button id="delete-group" class="delete-group__button">{{#if userType.owner}}{{#if chatType.group}}Удалить группу{{else}}Удалить канал{{/if}}{{else}}{{#if chatType.group}}Выйти из группы{{else}}Вый
исправил

2024-11-24 20:05 UTC, MoyStasik commented on source/entities/SearchedMessageCard/ui/SearchedMessageCard.ts
> +        }
сделал

2024-11-24 20:05 UTC, MoyStasik commented on source/entities/SearchedMessageCard/ui/SearchedMessageCard.ts
> +            let message : HTMLElement = chatMessages.querySelector("[id='" + messageId + "']")!;
исправил

2024-11-24 20:31 UTC, MoyStasik commented on source/entities/SearchedMessageCard/ui/SearchedMessageCard.ts
> +                message = chatMessages.querySelector("[id='" + messageId + "']")!;
исправил

2024-11-24 20:35 UTC, MoyStasik commented on source/widgets/AddChannelForm/index.ts
добавил экспорт

2024-11-24 20:38 UTC, MoyStasik commented on source/widgets/AddChannelForm/lib/types.ts
> +export interface UserType{
это сделал для handlebars, там нельзя логические операции делать

2024-11-24 20:38 UTC, MoyStasik commented on source/widgets/Chat/ui/Chat.handlebars
> +    {{#if userType.owner}}
ругается

2024-11-24 20:39 UTC, MoyStasik commented on source/widgets/Chat/ui/Chat.ts
> +            "/messages/" + messageId,
сделал

2024-11-24 20:52 UTC, MoyStasik commented on source/widgets/DeleteMessage/ui/DeleteMessage.ts
> +export class DeleteMessage {
не хотел handlebars засорять, перенес в feature

2024-11-24 20:59 UTC, MoyStasik commented on source/widgets/Chat/ui/Chat.ts
> +        //chatMessage.renderNewMessage(message);
убрал

2024-11-24 20:59 UTC, MoyStasik commented on source/pages/MainPage/ui/handlers.ts
> +  // if (message.authorID === UserStorage.getUser().id) {
убрал

2024-11-24 21:11 UTC, MoyStasik commented on source/widgets/ChatList/ui/ChatList.handlebars
> +      <hr style="width: 95%; opacity: 0.6;">
убрал

2024-11-24 21:32 UTC, MoyStasik commented on source/widgets/DeleteMessage/ui/DeleteMessage.ts
> +                spanDelete.textContent = "Вы не можете удалять чужие сообщения";
сделал проверку

2024-11-24 21:32 UTC, MoyStasik commented on source/widgets/Chat/ui/Chat.ts
> +        }
кавычки убрал, типизация нужна для handlebars

2024-11-24 21:35 UTC, MoyStasik commented on source/widgets/Chat/ui/Chat.ts
> +              const index = profileUser.findIndex((elem) => {
сделал

2024-11-24 21:47 UTC, MoyStasik commented on source/widgets/Chat/ui/Chat.ts
> +      searchImageContainer.style.display = "flex";
исправил

2024-11-24 22:12 UTC, MoyStasik commented on source/widgets/Chat/ui/Chat.ts
> +    }
для handlebars

2024-11-24 22:30 UTC, MoyStasik commented on source/widgets/ChatList/ui/ChatList.ts
> +          chatList.style.display = "none";
исправил

2024-11-24 23:35 UTC, MoyStasik commented on source/entities/ChatMessage/ui/ChatMessage.ts
> +        const messageId = event.target.id;
сделал

2024-11-25 00:11 UTC, rissenberg requested changes

2024-11-25 00:11 UTC, rissenberg commented on source/widgets/Chat/ui/Chat.scss
> +.hiden {
опечатка

2024-11-25 00:11 UTC, rissenberg commented on source/widgets/Chat/ui/Chat.scss
> +.flex {
не нужен - пиши дисплей в основном классе компонента

2024-11-25 00:11 UTC, rissenberg commented on source/widgets/ContactsList/ui/ContactsList.scss
> +.hiden {
не нужно дублировать код - у тебя же есть уже одно объявление

2024-11-25 00:12 UTC, MoyStasik commented on source/widgets/Chat/ui/Chat.scss
> +.hiden {
поправил

2024-11-25 00:14 UTC, MoyStasik commented on source/widgets/Chat/ui/Chat.scss
> +.flex {
убрал

2024-11-25 00:39 UTC, rissenberg approved these changes

2024-11-25 00:39 UTC, merged