PFN-56
frontend-park-mail-ru/2024_2_EaglesDesigners pull request #6
Opened 2024-09-27 18:42 UTC by MoyStasik

Добавил класс для взаимодействия с api. Ссылка на задачу - https://ru.yougile.com/team/343b17e1c7b0/#PFN-56

2024-09-27 21:38 UTC, rissenberg requested changes

2024-09-27 21:38 UTC, rissenberg commented on source/shared/api/api.js
> +class ApiResponse{
Не вижу смысла в этом классе, давай пропустим его создание

2024-09-27 21:38 UTC, rissenberg commented on source/shared/api/api.js
> +export const api = new Api();
такие штуки обычно экспортирутся капсом - API

2024-09-27 21:38 UTC, rissenberg commented on source/shared/api/api.js
> +            return new ApiResponse(json, null);
здесь просто вернем json

2024-09-27 21:38 UTC, rissenberg commented on source/shared/api/api.js
> +        let response = await fetch(url);
обернем все это в try-catch и будем возвращать при ошибке объект типа `{ error: "could not fetch" }` или придумай описание получше

2024-09-27 21:38 UTC, rissenberg commented on source/shared/api/api.js
> +            return new ApiResponse(null, json.error);
У нас при ошибке и при статусе 200 по идее возвращается одно и то же - тело ответа. if тут не нужен

2024-09-27 21:38 UTC, rissenberg commented on source/shared/api/api.js
> +        const response = await fetch(url, {
Тут тоже оберни в try-catch

2024-09-27 21:38 UTC, rissenberg commented on source/index.js
> +if (response.error != null) {
Нет, это как раз нужно в App писать, и при этой проверке решать, отрисовывать ли страницу логина или страницу чатов

2024-09-27 21:38 UTC, rissenberg commented on source/index.js
> +if (response.error != null) {
А инициализацию приложения оставь. Все таки страницы чатов и логина это часть нашего приложения, правда?

2024-09-27 21:38 UTC, rissenberg commented on source/index.js
> +if (response.error != null) {
и проверку на null и undefined не обязательно делать явной - достаточно просто писать это поле - `if (response.error)`

2024-09-27 21:38 UTC, rissenberg commented on source/widgets/loginForm/loginForm.js
>              this.#parent.removeChild(this.#parent.querySelector('#left'));
Удаления тут не нужны, потоу что все равно будет переписан root

2024-09-27 21:38 UTC, rissenberg commented on source/shared/api/api.js
> +            return new ApiResponse(json, null);
Точнее, его поле body. Ничего проме него не должно выходить за пределы этого класса

2024-09-27 21:38 UTC, rissenberg commented on source/widgets/loginForm/loginForm.js
> +            if (response.ok) {
Здесь можно просто проверять наличие поля error в rsponse. если тебе этого не достаточно, то в классе api добавить при return еще одно поле `isError: !json.ok`

2024-09-27 21:38 UTC, rissenberg commented on source/widgets/loginForm/loginForm.js
> +                this.#parent.removeChild(this.#parent.querySelector('#left'));
Не нужны

2024-09-27 22:21 UTC, MoyStasik commented on source/shared/api/api.js
> +class ApiResponse{
убрал

2024-09-27 22:21 UTC, MoyStasik commented on source/shared/api/api.js
> +export const api = new Api();
сделал

2024-09-27 22:21 UTC, MoyStasik commented on source/shared/api/api.js
> +            return new ApiResponse(json, null);
сделал

2024-09-27 22:22 UTC, MoyStasik commented on source/shared/api/api.js
> +        let response = await fetch(url);
сделал

2024-09-27 22:22 UTC, MoyStasik commented on source/shared/api/api.js
> +            return new ApiResponse(null, json.error);
сделал

2024-09-27 22:22 UTC, MoyStasik commented on source/shared/api/api.js
> +        const response = await fetch(url, {
сделал

2024-09-27 22:22 UTC, MoyStasik commented on source/index.js
> +if (response.error != null) {
сделал

2024-09-27 22:22 UTC, MoyStasik commented on source/index.js
> +if (response.error != null) {
сделал

2024-09-27 22:23 UTC, MoyStasik commented on source/widgets/loginForm/loginForm.js
>              this.#parent.removeChild(this.#parent.querySelector('#left'));
сделал

2024-09-27 22:23 UTC, MoyStasik commented on source/widgets/loginForm/loginForm.js
> +            if (response.ok) {
сделал

2024-09-27 22:23 UTC, MoyStasik commented on source/widgets/loginForm/loginForm.js
> +                this.#parent.removeChild(this.#parent.querySelector('#left'));
убрал

2024-09-28 07:25 UTC, rissenberg requested changes

2024-09-28 07:25 UTC, rissenberg commented on source/shared/api/api.js
> +            return response.json()
return await

2024-09-28 07:25 UTC, rissenberg commented on source/shared/api/api.js
> +
Давай мы в конструкторе еще следующее напишем: у нас будет переменная базовый url, и для него будем передавать окончание пути. То есть переменная `baseUrl` будет создана пр конструкторе `new Api('https://backend.com/')` а в методах будет объединение с урлом переданным в аргументах: `const url = this.baseUrl + path`

2024-09-28 07:25 UTC, rissenberg commented on source/shared/api/api.js
> +    async get(url){
А тут вместо url переменную path для понятности

2024-09-28 07:25 UTC, rissenberg commented on source/shared/api/api.js
> +            let response = await fetch(url);
Перепиши все переменные на const и в будущем так их и старайся обозначать, let почти не используй

2024-09-28 07:25 UTC, rissenberg commented on source/widgets/loginForm/loginForm.js
> +                textLogin.textContent = 'Неверный логин или пароль';
Добавь return и убери блок else, так читать станет проще

2024-09-28 09:19 UTC, MoyStasik commented on source/shared/api/api.js
> +            return response.json()
исправил

2024-09-28 09:19 UTC, MoyStasik commented on source/shared/api/api.js
> +    async get(url){
поменял

2024-09-28 09:21 UTC, MoyStasik commented on source/shared/api/api.js
> +            let response = await fetch(url);
исправил

2024-09-28 20:55 UTC, rissenberg approved these changes

2024-09-28 20:58 UTC, merged